version: '2.3'

services:
  files:
    build:
      context: .
    volumes:
      - "./:/service"
    environment:
      - PYTHONPATH="/service"
      - REDIS_URL=redis://redis
      - DATABASE_URL=postgresql://postgres@postgres:5432/postgres
      - DATABASE_CONNECTION_POOL_URL=postgresql://postgres@postgres:5432/postgres
      - MASTER_KEY=${MASTER_KEY:-KTVciAUQFpFh2WdJ/oiHJlxl6FvzRZp8kYzAAv3l2OA=}
      - DOMAIN=localhost
      - IMGUR_KEY=vcxvdfgfc6r554etrgd
      - SITE_NAME=VidyaCafe
      - CLOUDFLARE_ZONE=vcxvdfgfc6r554etrgd
      - CLOUDFLARE_KEY=vcxvdfgfc6r554etrgd
      - MAILGUN_KEY=vcxvdfgfc6r554etrgd
      - MAILGUN_DOMAIN=asdf
      - FORCE_HTTPS=0
      - DISCORD_SERVER_ID=vcxvdfgfc6r554etrgd
      - DISCORD_CLIENT_ID=vcxvdfgfc6r554etrgd
      - DISCORD_CLIENT_SECRET=vcxvdfgfc6r554etrgd
      - DISCORD_BOT_TOKEN=vcxvdfgfc6r554etrgd
      - FACEBOOK_TOKEN=vcxvdfgfc6r554etrgd
      - STEAM_KEY=B9470579F3988522EA673CE54FA084BC
     #- HCAPTCHA_SITEKEY=vcxvdfgfc6r554etrgd
      - HCAPTCHA_SECRET=vcxvdfgfc6r554etrgd
      - YOUTUBE_KEY=vcxvdfgfc6r554etrgd
      - PUSHER_KEY=vcxvdfgfc6r554etrgd
      - SPAM_SIMILARITY_THRESHOLD=0.5
      - SPAM_SIMILAR_COUNT_THRESHOLD=5
      - SPAM_URL_SIMILARITY_THRESHOLD=0.1
      - COMMENT_SPAM_SIMILAR_THRESHOLD=0.5
      - COMMENT_SPAM_COUNT_THRESHOLD=5
      - READ_ONLY=0
      - BOT_DISABLE=0
      - COINS_NAME=Sips
      - DOOM_CAPTCHA=true
    links:
      - "redis"
      - "postgres"
    ports:
      - "80:80"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    volumes:
      - ./redis.conf:/drama/redis.conf
    ports:
      - "6379:6379"

  postgres:
    image: postgres:12.3
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/00-schema.sql"
      - "./seed-db.sql:/docker-entrypoint-initdb.d/01-schema.sql"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
